# Generated by Django 5.0.2 on 2024-02-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_student_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='D:\\it-run-project\\mysite\\media'),
        ),
    ]
