# Generated by Django 5.0.2 on 2024-02-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='D:\\it-run-project\\mysite\\media\\images'),
        ),
    ]
